//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThailandAddress.Initializer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaInfo
    {
        public AreaInfo()
        {
            this.SubAreaInfoes = new HashSet<SubAreaInfo>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int ProvinceId { get; set; }
    
        public virtual ProvinceInfo ProvinceInfo { get; set; }
        public virtual ICollection<SubAreaInfo> SubAreaInfoes { get; set; }
    }
}
