//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThailandAddress.Initializer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvinceInfo
    {
        public ProvinceInfo()
        {
            this.AreaInfoes = new HashSet<AreaInfo>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int GeographyId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AreaInfo> AreaInfoes { get; set; }
        public virtual GeographyInfo GeographyInfo { get; set; }
    }
}
