//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThailandAddress.Initializer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubAreaInfo
    {
        public SubAreaInfo()
        {
            this.PostalCodeInfoes = new HashSet<PostalCodeInfo>();
        }
    
        public int Id { get; set; }
        public int AreaId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual AreaInfo AreaInfo { get; set; }
        public virtual ICollection<PostalCodeInfo> PostalCodeInfoes { get; set; }
    }
}
