//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThailandAddress.Initializer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThailandAddressMsSqlEntities : DbContext
    {
        public ThailandAddressMsSqlEntities()
            : base("name=ThailandAddressMsSqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AreaInfo> AreaInfoes { get; set; }
        public DbSet<GeographyInfo> GeographyInfoes { get; set; }
        public DbSet<PostalCodeInfo> PostalCodeInfoes { get; set; }
        public DbSet<ProvinceInfo> ProvinceInfoes { get; set; }
        public DbSet<SubAreaInfo> SubAreaInfoes { get; set; }
    }
}
